/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zsy_frame_sample_jni_control_android_hello_c_HelloCJni */

#ifndef _Included_com_zsy_frame_sample_jni_control_android_hello_c_HelloCJni
#define _Included_com_zsy_frame_sample_jni_control_android_hello_c_HelloCJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zsy_frame_sample_jni_control_android_hello_c_HelloCJni
 * Method:    hellFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zsy_frame_sample_jni_control_android_hello_c_HelloCJni_hellFromC
  (JNIEnv *, jobject);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_hello_c_HelloCJni
 * Method:    hell_from_c
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zsy_frame_sample_jni_control_android_hello_c_HelloCJni_hell_1from_1c
  (JNIEnv *, jobject);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_hello_c_HelloCJni
 * Method:    hell_1from_1c
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zsy_frame_sample_jni_control_android_hello_c_HelloCJni_hell_11from_11c
  (JNIEnv *, jobject);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_hello_c_HelloCJni
 * Method:    utf_gbk_1c
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zsy_frame_sample_jni_control_android_hello_c_HelloCJni_utf_1gbk_11c
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
