/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zsy_frame_sample_jni_control_android_aes_AesJni */

#ifndef _Included_com_zsy_frame_sample_jni_control_android_aes_AesJni
#define _Included_com_zsy_frame_sample_jni_control_android_aes_AesJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zsy_frame_sample_jni_control_android_aes_AesJni
 * Method:    AES_Encrypt
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_zsy_frame_sample_jni_control_android_aes_AesJni_AES_1Encrypt
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_aes_AesJni
 * Method:    AES_Decrypt
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_zsy_frame_sample_jni_control_android_aes_AesJni_AES_1Decrypt
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
