/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zsy_frame_sample_jni_control_android_mutual_javacallc_MutualProvider */

#ifndef _Included_com_zsy_frame_sample_jni_control_android_mutual_javacallc_MutualProvider
#define _Included_com_zsy_frame_sample_jni_control_android_mutual_javacallc_MutualProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zsy_frame_sample_jni_control_android_mutual_javacallc_MutualProvider
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_zsy_frame_sample_jni_control_android_mutual_javacallc_MutualProvider_add__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_mutual_javacallc_MutualProvider
 * Method:    add
 * Signature: (CC)C
 */
JNIEXPORT jchar JNICALL Java_com_zsy_frame_sample_jni_control_android_mutual_javacallc_MutualProvider_add__CC
  (JNIEnv *, jobject, jchar, jchar);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_mutual_javacallc_MutualProvider
 * Method:    sayHelloInC
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zsy_frame_sample_jni_control_android_mutual_javacallc_MutualProvider_sayHelloInC
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_mutual_javacallc_MutualProvider
 * Method:    intMethod
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_zsy_frame_sample_jni_control_android_mutual_javacallc_MutualProvider_intMethod
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_mutual_javacallc_MutualProvider
 * Method:    byteMethod
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_zsy_frame_sample_jni_control_android_mutual_javacallc_MutualProvider_byteMethod
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_mutual_javacallc_MutualProvider
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_zsy_frame_sample_jni_control_android_mutual_javacallc_MutualProvider_sub
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
