/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zsy_frame_sample_jni_control_android_mutual_ccalljava_CcalljavaAct */

#ifndef _Included_com_zsy_frame_sample_jni_control_android_mutual_ccalljava_CcalljavaAct
#define _Included_com_zsy_frame_sample_jni_control_android_mutual_ccalljava_CcalljavaAct
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zsy_frame_sample_jni_control_android_mutual_ccalljava_CcalljavaAct
 * Method:    call_activity_method1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zsy_frame_sample_jni_control_android_mutual_ccalljava_CcalljavaAct_call_1activity_1method1
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
