/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zsy_frame_sample_jni_control_android_mutual_ccalljava_CallbackProvider */

#ifndef _Included_com_zsy_frame_sample_jni_control_android_mutual_ccalljava_CallbackProvider
#define _Included_com_zsy_frame_sample_jni_control_android_mutual_ccalljava_CallbackProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zsy_frame_sample_jni_control_android_mutual_ccalljava_CallbackProvider
 * Method:    callmethod1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zsy_frame_sample_jni_control_android_mutual_ccalljava_CallbackProvider_callmethod1
  (JNIEnv *, jobject);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_mutual_ccalljava_CallbackProvider
 * Method:    callmethod2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zsy_frame_sample_jni_control_android_mutual_ccalljava_CallbackProvider_callmethod2
  (JNIEnv *, jobject);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_mutual_ccalljava_CallbackProvider
 * Method:    callmethod3
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zsy_frame_sample_jni_control_android_mutual_ccalljava_CallbackProvider_callmethod3
  (JNIEnv *, jobject);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_mutual_ccalljava_CallbackProvider
 * Method:    callmethod4
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zsy_frame_sample_jni_control_android_mutual_ccalljava_CallbackProvider_callmethod4
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
