/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zsy_frame_sample_jni_control_android_hello_cpp_HelloCppCJni */

#ifndef _Included_com_zsy_frame_sample_jni_control_android_hello_cpp_HelloCppCJni
#define _Included_com_zsy_frame_sample_jni_control_android_hello_cpp_HelloCppCJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zsy_frame_sample_jni_control_android_hello_cpp_HelloCppCJni
 * Method:    hellFromCPP
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zsy_frame_sample_jni_control_android_hello_cpp_HelloCppCJni_hellFromCPP__
  (JNIEnv *, jobject);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_hello_cpp_HelloCppCJni
 * Method:    hellFromCPP
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zsy_frame_sample_jni_control_android_hello_cpp_HelloCppCJni_hellFromCPP__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
