/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zsy_frame_sample_jni_control_android_assets_AssetsJni */

#ifndef _Included_com_zsy_frame_sample_jni_control_android_assets_AssetsJni
#define _Included_com_zsy_frame_sample_jni_control_android_assets_AssetsJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zsy_frame_sample_jni_control_android_assets_AssetsJni
 * Method:    readFromAssets
 * Signature: (Landroid/content/res/AssetManager;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zsy_frame_sample_jni_control_android_assets_AssetsJni_readFromAssets
  (JNIEnv *, jclass, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
